version: "3"

services:
  next-app:
    container_name: pedemais-home
    build:
      context: .
      dockerfile: prod.Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "3001:3000"